### ISSUE TITLE
Report making needs optimization

### ISSUE THREAD

**Issue by PierrePaul** [PierrePaul/wifipunch#2]
https://github.com/PierrePaul/wifipunch/blob/master/wifipunch/api/reports.py#L114
When doing the report, we should filter the timelogs before fetching them all from the database.

**Comment by abondis** [comment]
@PierrePaul ça devrait le faire déja, via https://github.com/PierrePaul/wifipunch/blob/master/wifipunch/api/reports.py#L69 puis  https://github.com/PierrePaul/wifipunch/blob/master/wifipunch/api/reports.py#L103 qui build la query avant de faire `.all()`
Par défaut ça devrait prendre juste une semaine, et il est possible de spécifier les dates dans la query.

**Comment by abondis** [comment]
aussi, il y a ça pour des exemples, quand j'avais testé ça fonctionnait, mais peut-être que depuis un bug est apparu ?
https://github.com/PierrePaul/wifipunch/blob/master/wifipunch/test_api.sh#L30

**Comment by PierrePaul** [comment]
Thanks for the clear up. Tests are also working without any issue.
